### ISSUE TITLE
Incorrect IP

### ISSUE THREAD

**Issue by PhikalDo** [jghaanstra/com.doorbird#20] opened 2021-05-25 15:34 UTC
Hi,
If I try to conncect my Doorbird device to my Homey it gives a incorrect IP-adress and the proces cannot be completed.

**Comment by jghaanstra** [comment] 2021-05-25 15:54
The IP address is returned by the DoorBird itself through mDNS. Is this is not the correct IP address you probably need to reset the DoorBird.

**Comment by PhikalDo** [comment] 2021-05-25 16:03
Hi,

Thanks, I tried, but same incorrect IP appears. I check the actual IP address and are able to connect to the Doorbird via a browser using the correct IP…

**Comment by jghaanstra** [comment] 2021-05-25 16:09
Could you use a app to check the actual mDNS record like [service browser](https://play.google.com/store/apps/details?id=com.druk.servicebrowser&hl=nl&gl=US) for Android or [Flame browser](https://apps.apple.com/us/app/flame-services-browser/id325206381) for iOS to see what it returns as IP address.

**Comment by PhikalDo** [comment] 2021-05-25 19:02
When I use service browser I get the correct actual IP-address. The Homey app always state 169.254.103.61, which in not part of my network...

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by jghaanstra** [comment] 2021-05-25 19:52
There is not much I can do about this. I see this issue from time to time but the issue is with the DoorBird and not with my app. There is actually a dutch topic about this on the forum with no solution though. https://community.athom.com/t/doorbird-pairen/40434/4

You will have to contact DoorBird and explain your situation.

**Comment by PhikalDo** [comment] 2021-05-26 06:55
I see, thanks, I will contact Doorbird tech team. Would it be an option to update the app with the option to enter the correct IP-address yourselfe so we dont depend on Doorbird?


Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by jghaanstra** [comment] 2021-05-26 07:00
That is already possible but only if no devices are discovered at all. What you could do is disconnect the DoorBird from your network, start the pairing wizard so the manual pairing screen appears since it will not discover any devices, then reconnect your DoorBird with your network and continu to pair it manually using the correct IP address.

I'm closing this since it's not actually an issue with my app.

**Closed by jghaanstra** 2021-05-26 07:00 UTC
Labels: waiting for user feedback
